### ISSUE TITLE
ID4. Return from fullscreen mode with button

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-pdf-consultations#41]

**Comment by paarals** [comment]
Hi @Naadjjaa, we want to confirm with you because right now there is a button to return:

Go to fullscreen mode:
![Image](https://github.com/stadtluzern/decidim-pdf-consultations/assets/40388743/2b15ae00-df2b-4f8b-8381-40cbc4b55fc0)

Back to fullscreen mode:
![Image](https://github.com/stadtluzern/decidim-pdf-consultations/assets/40388743/1c29cffe-c880-4d19-8904-f7868aa8793d)

Something that we miss?

**Comment by Naadjjaa** [comment]
@paarals I see. So my test participants (and I) didn't understand quickly enough that the same button leading to fullscreen mode can be used to exit it. Is it possible to replace the fullscreen icon only in the second view? E.g. with something like this:


![Image](https://github.com/stadtluzern/decidim-pdf-consultations/assets/75797851/2ff28ca4-a719-404b-8879-3885814de2ee)
