### ISSUE TITLE
BF3. "Boxing-Bugs" while preparing the participatory areas

### ISSUE THREAD

**Issue by Naadjjaa** [stadtluzern/decidim-pdf-consultations#42]
After setting a participatory area, its not easy to make changes to it:

- enlarge / make smaller is not working properly
- moving is only possible in the left corner, this is not found intuitively

We observed the following:

- sometimes deleted "boxes" are still visible in the front end
- when deleting a box, the numbers of sections do not adapt, the unconsistant numbering could be confusing for users
- when deleting a document and uploading another, the boxes from the old document still apear

Nice have:

- enable to draw boxes over more than one page without having to combine them manualy

**Comment by microstudi** [comment]
@Naadjjaa I'm going to start working on this one.
I have related question, I've seen that in you test you have done things like this:
![image](https://github.com/stadtluzern/decidim-pdf-consultations/assets/1401520/f8fa5595-e37f-4eaa-8153-1a1ef6d7bd45)

In this image, there are two overlapped sections, is this something that's going to happen? because it is going to be hard to handle, and probably to understand by the end user. However I'm not sure if you see some value in doing this, if it is the case we should study how to handle access to lowered sections.

**Comment by Naadjjaa** [comment]
@microstudi No, we will not do overlapping sections on purpose. This just happened because of the above described bugs.

**Comment by microstudi** [comment]
Thanks @Naadjjaa 
Do you think that you can detail a bit more these issues?:

- **enlarge / make smaller is not working properly:**
  I suppose you are talking about using the  '- / +` zoom section and then creating/editing boxes? What is that is not working properly? positions are not respected? Maybe a video would help!
Update: chrome is causing problems, firefox is working properly

- **moving is only possible in the left corner, this is not found intuitively**
  I guess you would prefer to use the whole box to move it. I found many problems trying to make it work this way, this is because the resize button. I'll give a second try, see if I can make it work. However, if it is not possible, do you have some suggestion to make it more clear that you need to use the icon?
Update: chrome is not showing the icons properly, firefox is workin properly

- **sometimes deleted "boxes" are still visible in the front end**
 Can you confirm that this happens after pressing the button "Save changes" and reloading afterwards the frontend?

- **enable to draw boxes over more than one page without having to combine them manualy**
  This is very complicated, because the PDF renderer library can present the pages in different ways, for instance you can pages side by side or pages one after the other. you can even flip pages. In this context any cross-page drawing is going to loose any meaning.

**Comment by paarals** [comment]
@Naadjjaa, also, could you tell us which browser are you using?

**Comment by Naadjjaa** [comment]
@paarals Normally Chrome Version 114.0.5735.91 (Offizieller Build) (64-Bit)
Edit: my colleage who reported the bugs uses: Microsoft Edge Version 113.0.1774.57 (Offizielles Build) (64-Bit)

**Comment by Naadjjaa** [comment]
@microstudi 

**enlarge / make smaller is not working properly:**
I asked for more feedback as I havent written this myself. Seems like a UX thing:
As process admin, when you create a participatory area (box) and then want to change the box, i.e. change the size (reduce, enlarge, widen, etc.), this is relatively laborious and does not work right away. It often happened to me that it created another box, which I didn't want at all. It is not clear how a created box can be resized.


**moving is only possible in the left corner, this is not found intuitively**
--> adding the icon for chrome will help

**sometimes deleted "boxes" are still visible in the front end**
Here again I asked for feedback from the person reporting it:
As process admin, when you delete a box that you have created and click on save changes, the box is deleted, but if you then close the editing and then create new boxes again at a later point in time, the deleted boxes still exist and there is a big mess. In addition, the deleted boxes are still displayed in the frontend and are not deleted. Boxes from the previous document are also displayed again in the back and front end.


**enable to draw boxes over more than one page without having to combine them manualy**
--> if it's that complicated we will leave it the way it is

**Comment by Naadjjaa** [comment]
@paarals @microstudi Important edit regarding the browser used by my colleague: Microsoft Edge
Version 113.0.1774.57 (Offizielles Build) (64-Bit)
